# Generated by Django 2.1.7 on 2019-04-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_auto_20190315_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
