# Generated by Django 2.1.5 on 2019-04-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_auto_20190402_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='answers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
